version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abcde
      POSTGRES_DB: user_db
    ports:
      - 5456:5432
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d/
  redis:
    image: redis
    ports:
      - 6379:6379
